repository: ../neo-sophia
extensions: ['.py', '.txt', '.yaml', '.yml', '.sh', '.md', '.toml']
db_path: .database/
cache_dir: .cache/
Tools:
  - module: groundcrew.tools
    tools:
      - CodebaseQATool
